protected/controllers/AjaxController.php
<?php

class AjaxController extends Controller
{
	public $layout = '//layouts/main';

	public function actionCalendar()
	{
		$model = new WhenIsCertificates();
		$data = array();
		foreach ($model as $when) {
			$data[] = array(
				'data' => date('Y') . '-' . $when['date_when'] . ' 00:00:00',
				"type" => "meeting",
				"title" => $when['name']
			);
		}
		echo json_encode($data);
	}

	public function actionAddToBasket($id = null, $price_id = null, $price = 0, $count = 1, $name='')
	{
		$cookie = (isset(Yii::app()->request->cookies['goods']->value)) ?
			Yii::app()->request->cookies['goods']->value : '';
		$cookie = json_decode($cookie, true);
		$all = 0;
		$all_price = 0;
		$data = array(array('id' => $id, 'price_id' => $price_id, 'price' => $price, 'count' => $count, 'name'=>$name));
		if (!empty($cookie) && !empty($cookie['goods'])) {
			$data = array_merge($cookie['goods'], $data);
		}
		foreach ($data as $good) {
			$all = $all + $good['count'];
			$all_price = $all_price + $good['price'];
		}
		$class = new stdClass();
		$class->goods = $data;
		$message = '<b>' . $all . '</b> СЕРТИФИКАТА<br/> НА СУММУ<br/><b>' . $all_price . '</b> РУБЛЕЙ';
		$class->in_basket = $message;
		$class = json_encode($class);
		$cookie = new CHttpCookie('goods', $class);
		$cookie->expire = time() + 60 * 60 * 24 * 180;
		Yii::app()->request->cookies['goods'] = $cookie;
		echo $message;

	}

	public function actionRemoveFromBasket($id = null, $price_id = null)
	{
		$cookie = (isset(Yii::app()->request->cookies['goods']->value)) ?
			Yii::app()->request->cookies['goods']->value : '';
		$cookie = json_decode($cookie, true);
		$all = 0;
		$all_price = 0;
		if (!empty($cookie) && !empty($cookie['goods'])) {
			$data = $cookie['goods'];
			$key_del = null;
			foreach ($data as $key => $good) {
				if ($good['id'] == $id && $good['price_id'] == $price_id) {
					$key_del = $key;
				}
			}
			unset($data[$key_del]);
			foreach ($data as $good) {
				$all = $all + $good['count'];
				$all_price = $all_price + $good['price'];
			}
			$class = new stdClass();
			$class->goods = $data;
			$class->in_basket = $all . ' СЕРТИФИКАТА НА СУММУ ' . $all_price . ' РУБЛЕЙ';
			$class = json_encode($class);
			$cookie = new CHttpCookie('goods', $class);
			$cookie->expire = time() + 60 * 60 * 24 * 180;
			Yii::app()->request->cookies['goods'] = $cookie;
			echo $all . ' СЕРТИФИКАТА НА СУММУ ' . $all_price . ' РУБЛЕЙ';
		}

	}

	public function actionIsAuth()
	{
		if (Yii::app()->user->id) {
			echo 1;
		} else {
			echo 0;
		}
	}
}

protected/controllers/CertificatesController.php
<?php

class CertificatesController extends Controller
{


	public function actionView($id)
	{
		$this->render('view', array('model' => Certificates::model()->findByPk($id)));
	}

	public function actionIndex()
	{
		$dataProvider = new CActiveDataProvider('Certificates');
		$this->render('index', array('dataProvider' => $dataProvider));
	}
}

protected/controllers/NewsController.php
<?php

class NewsController extends Controller
{

	public function actionView($id)
	{
		$this->render('view', array('model' => News::model()->findByPk($id)));
	}

	public function actionIndex()
	{
		$dataProvider = new CActiveDataProvider('News', array('pagination' => array('pageSize' => 25)));
		$this->render('index', array('dataProvider' => $dataProvider));
	}
}

protected/controllers/OrdersController.php
<?php

class OrdersController extends Controller
{

	public function filters()
	{
		return array('accessControl', 'postOnly + delete');
	}


	public function accessRules()
	{
		return array(
			array(
				'allow',
				'actions' => array('my'),
				'roles' => array(Users::AUTH_USER)
			),
			array(
				'allow',
				'actions' => array('basket'),
				'users' => array('*')
			),
			array('deny', 'users' => array('*')),
		);
	}

	public function actionMy()
	{
		$criteria = new CDbCriteria();
		$criteria->compare('user_id', Yii::app()->user->id);
		$model = Orders::model()->findAll($criteria);
		$this->render('my', array('model' => $model));
	}

	public function actionBasket()
	{
		$message = '';
		$model = (isset(Yii::app()->request->cookies['goods']->value)) ?
			Yii::app()->request->cookies['goods']->value : '';
		$model = json_decode($model, true);
		if (isset($_POST['Orders'])) {
			$cookie = (isset(Yii::app()->request->cookies['goods']->value)) ?
				Yii::app()->request->cookies['goods']->value : '';
			$cookie = json_decode($cookie, true);
			if (!empty($cookie)) {
				$new = new Orders();
				$new->user_id = Yii::app()->user->id;
				$new->current_status = Yii::app()->params['order_new'];
				$new->save();
				foreach ($cookie['goods'] as $good) {
					$goods = new OrderCertificates();
					$goods->order_id = $new->getPrimaryKey();
					$goods->certificate_id = $good['id'];
					$goods->price_id = $good['price_id'];
					$goods->save();

				}
				unset(Yii::app()->request->cookies['goods']);
				$message = 'Спасибо за заказ, наши операторы свяжутся с вами в ближайшее время';
			}
		}
		$this->render('basket', array('model' => $model, 'message' => $message));
	}

}

protected/controllers/PartnersController.php
<?php

class PartnersController extends Controller
{

	public function actionView($id)
	{
		$this->render('view', array('model' => Partners::model()->findByPk($id)));
	}

	public function actionIndex()
	{
		$dataProvider = new CActiveDataProvider('Partners', array('pagination' => array('pageSize' => 25)));
		$this->render('index', array('dataProvider' => $dataProvider));
	}
}

protected/controllers/PostsController.php
<?php

class PostsController extends Controller
{

	public function actionView($id)
	{
		$this->render('view', array('model' => News::model()->findByPk($id)));
	}

	public function actionIndex()
	{
		$dataProvider = new CActiveDataProvider('Posts', array('pagination' => array('pageSize' => 25)));
		$this->render('index', array('dataProvider' => $dataProvider));
	}
}

protected/controllers/SelloutsController.php
<?php

class SelloutsController extends Controller
{
	public $layout = '//layouts/main';

	public function actionView($id)
	{
		$this->render('view', array('model' => Sellouts::model()->findByPk($id)));
	}

	public function actionIndex()
	{
		$dataProvider = new CActiveDataProvider('Sellouts', array('pagination' => array('pageSize' => 25)));
		$this->render('index', array('dataProvider' => $dataProvider));
	}
}

protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	public $layout = '//layouts/main';

	public function actions()
	{
		return array(
			'captcha' => array('class' => 'CCaptchaAction', 'backColor' => 0xFFFFFF),
			'stat' => array('class' => 'CViewAction'),
		);
	}

	public function actionIndex()
	{
		$dataProvider = new CActiveDataProvider('Certificates');
		$this->render('//certificates/index', array('dataProvider' => $dataProvider));
	}

	public function actionError()
	{
		if ($error = Yii::app()->errorHandler->error) {
			if (Yii::app()->request->isAjaxRequest) {
				echo $error['message'];
			} else {
				$this->render('error', $error);
			}
		}
	}

	public function actionContact()
	{
		$model = new ContactForm;
		if (isset($_POST['ContactForm'])) {
			$model->attributes = $_POST['ContactForm'];
			if ($model->validate()) {
				$name = '=?UTF-8?B?' . base64_encode($model->name) . '?=';
				$subject = '=?UTF-8?B?' . base64_encode($model->subject) . '?=';
				$headers = "From: $name <{$model->email}>\r\n" .
					"Reply-To: {$model->email}\r\n" .
					"MIME-Version: 1.0\r\n" .
					"Content-Type: text/plain; charset=UTF-8";

				mail(Yii::app()->params['adminEmail'], $subject, $model->body, $headers);
				Yii::app()->user->setFlash(
					'contact',
					'Ваше письмо отправлено. Мы неприменно вам ответим в ближайшее время.'
				);
				$this->refresh();
			}
		}
		$this->render('contact', array('model' => $model));
	}

	public function actionSearch()
	{
		$model = new SearchCertificates();
		$model->attributes = $_GET['SearchCertificates'];
		$dataProvider = $model->getResult();
		$this->render('//certificates/index', array('dataProvider' => $dataProvider, 'model' => $model));
	}
}

protected/views/certificates/_view.php
<div class="column lf-column inline">
	<div class="column">
		<div class="thumb"><?php echo $data->image(184, 184); ?></div>
		<div class="price">
			<span class="nominal">300</span> рублей
		</div>
	</div>
	<div class="column info">
		<h3><a href="<?php echo Yii::app()->createUrl('certificates/view', array('id' => $data->id)); ?>">Сертификат
				"<?php echo $data->name; ?>"</a></h3>

		<p>Только вы знаете, что ей нужно 8 марта. Но только она сама снова должна это выбрать для себя...</p>
		<a href="#" class="detail" onclick="showDetailPopup(1);return false;">Подробнее</a><br/>
		<a id="<?php echo $data->id; ?>" price_id="<?php echo $data->price[0]->price->id; ?>"
		   name="<?php echo $data->name; ?>"
		   price="<?php echo $data->price[0]->price->price; ?>"
		   href="#" class="order-button rounded addtoBasket ">Заказать</a>
	</div>
	<div class="clear"></div>
</div>

protected/views/certificates/index.php
<div class="gift-items table" id="giftList">
	<div class="row">
		<?php $this->widget('zii.widgets.CListView', array('dataProvider' => $dataProvider, 'itemView' => '//certificates/_view')); ?>
	</div>
</div>

protected/views/certificates/view.php
<h1>View News #<?php echo $model->id; ?></h1>
<?php echo $model->image(200, 200); ?>
<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'title',
		'anons',
		'content',
		'date_add',
	),
)); ?>

protected/views/posts/_view.php
<div class="view">
	<?php echo CHtml::link(
		$data->title,
		Yii::app()->createUrl('posts/view', array('id' => $data->id))
	); ?>
	<br />

	<?php echo $data->image(100, 100); ?>
	<br />

	<?php echo CHtml::encode($data->anons); ?>
	<br />

	<?php echo $data->content; ?>
	<br />

	<?php echo CHtml::encode($data->date_add); ?>
	<br />
	<?php echo CHtml::encode($data->partner_id); ?>
	<br />
</div>

protected/views/posts/index.php
<h1>Интересное</h1>
<?php $this->widget('zii.widgets.CListView', array('dataProvider'=>$dataProvider,'itemView'=>'_view')); ?>

protected/views/posts/view.php
<h1>View Posts #<?php echo $model->id; ?></h1>
<?php echo $model->image(200, 200); ?>
<?php $this->widget(
	'zii.widgets.CDetailView',
	array(
		'data' => $model,
		'attributes' => array(
			'id',
			'title',
			'anons',
			'content',
			'date_add',
		),
	)
); ?>

protected/views/sellouts/_view.php
<div class="view">
	<?php echo $data->image(); ?>
	<br/>
	<b>Наименование</b>: <?php echo CHtml::link(
		$data->name,
		Yii::app()->createUrl('sellouts/view', array('id' => $data->id))
	); ?>
	<br/>
	<b>Анонс</b>: <?php echo $data->anons; ?>
	<br/>
	<b>Дата окончания</b>: <?php echo $data->lifetime; ?>
	<br/>
</div>

protected/views/sellouts/index.php
<h1>Акции</h1>
<?php $this->widget('zii.widgets.CListView', array('dataProvider'=>$dataProvider,'itemView'=>'_view')); ?>

protected/views/sellouts/view.php
<div class="view">
	<?php echo $model->image(200, 200); ?>
	<br/>
	<b>Наименование</b>: <?php echo CHtml::encode($model->name); ?>
	<br/>
	<b>Анонс</b>: <?php echo $model->anons; ?>
	<br/>
	<b>Скидка</b>: <?php echo CHtml::encode($model->discount); ?> %
	<br/>
	<b>Дата окончания</b>: <?php echo $model->lifetime; ?>
	<br/>
	<?php echo CHtml::link('Сертификаты', Yii::app()->createUrl('certificates/sellouts', array('id' => $model->id))); ?>
</div>